on: ["push", "pull_request"]

name: Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: npm install
      run: |
        npm install
        npm run pretest
        npm run test

    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        format: lcov
        debug: true
        allow-empty: false